try {}
// ⚠️ Potential issue: missing catch param identifier in throw statement
catch (e) {
  throw new Error('something')
}
