try {}
catch (e) {
  throw new Error('something')
}
